### ISSUE TITLE
Unable to build again node 0.11.14-pre/libyaml 2.0.2

### ISSUE THREAD

**Issue by dshadowwolf** [stephank/yaml.node#8]
Either there is a problem with my compiler (gcc 4.8.2) or there is a very strange problem going on with the source code.

Line 483 marks the closing curly-bracket for 'static Handle&lt;Value&gt; Event()' and the previous line is a return statement with no obvious way for the compiler to mistake it for anything else. But attempts to build both the version distributed by npm and the git repository always end with:

../binding.cc: In static member function ‘static v8::Handle&lt;v8::Value&gt; yaml::Emitter::Event(const int&)’:
../binding.cc:483:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^

Help would be wonderful!

**Comment by stephank** [comment]
There is no libyaml 2.0.2? But, there's no need to install it, the package bundles libyaml.

What platform are you compiling on? Is it the default compiler for that platform, or a custom one?

It looks like these warnings can also trigger on compiler generated code. But it's an odd warning, that's for sure.

I haven't tried this library on node 0.11. Be warned that I'm not dogfooding this anymore.

**Comment by stephank** [comment]
According to travis, it's more than a little broken on node 0.11.3:
https://travis-ci.org/stephank/yaml.node/jobs/28861787

I'm not sure if warnings are even the cause of your failing build. Don't believe node-gyp puts `-Werror` in cflags? Aren't there any errors in your output?

I'm inclined to call this a duplicate of #7.

**Comment by dshadowwolf** [comment]
Mint 17, default compiler... Hrm, looking at the spew of warnings more, it appears to actually be something different. 

/home/madman/source/node-git/deps/v8/include/v8.h:816:13: error: 'v8::HandleScope::HandleScope()' is protected
   V8_INLINE HandleScope() {}
             ^
../binding.cc:489:17: error: within this context
     HandleScope scope;
                 ^
../binding.cc:503:32: error: 'New' is not a member of 'v8::String'
     Local<Value> params[1] = { String::New(string, size) };
                                ^
../binding.cc:504:22: error: base operand of '->' has non-pointer type 'v8::Persistentv8::Function'
     e->writeCallback_->Call(Context::GetCurrent()->Global(), 1, params);
                      ^
../binding.cc:504:29: error: 'GetCurrent' is not a member of 'v8::Context'
     e->writeCallback_->Call(Context::GetCurrent()->Global(), 1, params);

So my initial thought was absolutely wrong and probably because of the hour at which I was attempting the build.

**Comment by dshadowwolf** [comment]
I have started work on correcting the flood of errors I get when building against node 0.11 -- shall I post a pull when I have the work ready here or over on #7 ?

**Comment by stephank** [comment]
As mentioned in #7, I don't know how node is going to tackle this problem. There's talks of a compatibility layer, and we should probably wait for it.

Current state of things is that getting it to work on 0.11 breaks on 0.10, so I can't accept a straight port.

**Comment by dshadowwolf** [comment]
no problem, I'll just maintain it locally for myself, then. However... the problem here is that the V8 API has changed in an incompatible manner and it is likely that Node should have had its own interface layer between V8 and its add-ons already :)

**Comment by dshadowwolf** [comment]
I have managed to fully port it - didn't take long - but it is no longer compatible with older versions of Node/V8. Only problem I had is that the version_info stuff was causing a segfault when I tried accessing it. No idea why and it seems that it wasn't needed.

If anyone wants to see this code, I will fork the tree on github and push out my changes.
